name: Coot CI Windows

on:
   schedule:
   - cron: "1 1 1,4 * *"

jobs:

  build-for-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run:  bash ./build-it-win ; echo done

    - name: Upload build logs
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-public-html-package
        path: /c/Users/runneradmin/public_html
        retention-days: 3

